import department1Png from "images/collections/department1.png";
import department2Png from "images/collections/department2.png";
import department3Png from "images/collections/department3.png";
import department4Png from "images/collections/department4.png";
import kitchendepartment from "images/collections/kitchendepartment.png";
import homedepartment from "images/collections/homedepartment.png";
import electronicsdepartment from "images/collections/electronicsdepartment.png";
import officedepartment from "images/collections/officedepartment.png";
import cosmeticsdepartment from "images/collections/cosmeticsdepartment.png";
import beautydepartment from "images/collections/beautydepartment.png";

export const COLORS: string[] = [
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
  "bg-indigo-100",
  "bg-slate-100",
  "bg-sky-100",
  "bg-orange-100",
];




export const IMAGES: string[] = [
  kitchendepartment,
  homedepartment,
  electronicsdepartment,
  officedepartment,
  cosmeticsdepartment,
  department2Png,
  beautydepartment,
  department3Png,
  department4Png,
  department1Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
  department1Png,
  department2Png,
  department3Png,
  department4Png,
];